version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  producer:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
      - INTERVAL=5
    depends_on:
      - rabbitmq

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "consumer.py"]
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
